### ISSUE TITLE
rename CaretsHistory

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/CudaText-registry#4]
add space.

**Comment by kvichans** [comment]
не понимаю, что хотите - дайте PR

**Comment by Alexey-T** [comment]
PR не хватит

- переименовать файл CaretHistory.zip -дать "_"
- поправить ссылку в этом гх

**Comment by kvichans** [comment]
Аааа - ок

**Comment by kvichans** [comment]
zip переименовал и выложил на СФ
старый zip удалил
в kv-addons.json указал новый zip и обновил в ГХ

**Comment by Alexey-T** [comment]
спасибо
